test:
  containers:
    - name: mongo
      image: mongo:4.0.3
deploy:
  internalPort: 3000
  env:
    MONGO_HOST: mongodb-scratch.digital-cloud.svc.cluster.local
    MONGO_DB: people
    MONGO_USER: master
    MONGO_SSL_CA: /app/rds.pem
    DEBUG: app:*,lib:*,dbg:*
    LISTENER_AUTH_RELAX_CREDENTIALS: true
