test:
  containers:
    - name: mongo
      image: mongo:4.0.3
deploy:
  internalPort: 3000
  env:
    MONGO_HOST: mongodb-scratch.digital-cloud.svc.cluster.local
    # MONGO_REPLICA_SET: rs0
    #MONGO_DB: people-{{env}}
    MONGO_DB: people
    #NODE_ENV: {{env}}
    DEBUG: app:*,lib:*,dbg:*
